# Creating Timeseries from ownership data

### This notebook will join together the monthly ownership data from 2022-2024 into  time-series with 36 monthly time stamps

In [38]:
from pathlib import Path
import sys

project_dir = Path().resolve().parent.parent

sys.path.append(str(project_dir))
from config import PATHS
import pandas as pd
import numpy as np

In [39]:
ownership_path = PATHS.ownership_data

In [40]:
data_dict = {}
for file in ownership_path.glob("*.txt"):
    date_part = file.stem.split("-")[-2] + "_" + file.stem.split("-")[-1]
    variable_name = f"data_{date_part}"

    df = pd.read_csv(file, sep="|")  

    data_dict[variable_name] = df

In [41]:
combined_data = pd.concat(data_dict.values())
combined_data.sort_values(by=["Code", "Date"], inplace=True)
combined_data["Date"] = pd.to_datetime(combined_data["Date"], format="%d-%b-%Y")

In [42]:
grouped_data = {code: group for code, group in combined_data.groupby("Code")}

In [43]:
for code, df in grouped_data.items():
    grouped_data[code] = df.sort_values(by="Date").reset_index(drop=True)

In [44]:
print(len(grouped_data))

5068

In [46]:
grouped_data['BBCA'].head()

        Date  Code    Type  ...  Foreign FD   Foreign OT      Total.1
0 2022-01-31  BBCA  EQUITY  ...   699503832   9858510117  43978631276
1 2022-02-25  BBCA  EQUITY  ...   699727532  10024379008  44181261174
2 2022-03-31  BBCA  EQUITY  ...   696297632  10108109884  44198538867
3 2022-04-28  BBCA  EQUITY  ...   696328132  10142348594  44513697598
4 2022-05-31  BBCA  EQUITY  ...   690333132  10331971867  43998583144

[5 rows x 25 columns]

In [47]:
#output_directory = PATHS.outputs/"ownership-data-timeseries"
#for code, df in grouped_data.items():
#    df.to_csv(f"{output_directory}/{code}_time_series.csv")